### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by florenciagomez7** [AnitaMigueles/Mercado-Liebre#1]
1- Cumple: contiene todos los elementos requeridos en el header, main y footer.
2- Cumple: los artículos e iconos tienen el tamaño requerido y están bien ubicados.
3- Cumple: el sitio es responsive.
4- Cumple: el sitio cuenta con un "register".
5- Cumple: el sitio cuenta con un "login".
6- Cumple: se muestra un mensaje de "error".
7- Cumple: el search bar es un formulario.
8- Cumple: contiene animaciones.
9- Todo está bien ubicado y tal como se lo había requerido.
10- No creo que haya mucho por mejorar. Quizás el tamaño del logo en la resolución para computadora (hacerlo más grande), y el margen (en la MacBook) entre el precio y el descuento, también en la resolución para computadora (+1200px). 
Aprox en los 1024 px, la cafetera pierde el margen entre el precio y el descuento también.

**Comment by AnitaMigueles** [comment]
Gracias Flor!!
