### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by alegon23** [AnitaMigueles/Mercado-Liebre#2]
- [ ] 1. Cada sección tiene el contenido que se pide.
- [ ] 2. El contenido del footer está centrado, pero no está ubicado correctamente, ya que debería verse de forma horizontal (row) para desktop. Los íconos y lo demás está todo bien.
- [ ] 3. El sitio sí se adapta a distintas resoluciones de pantalla.
- [ ] 4. El sitio cuenta con formulario de registro.
- [ ] 5. El sitio cuenta con formulario de login.
- [ ] 6. Sí se muestran mensajes de error.
- [ ] 7. El search bar sí es un formulario.
- [ ] 8. Sí se utilizan transiciones de CSS
- [ ] 9. En general el sitio es muy bueno y cumple con todas las consignas 🥳
- [ ] 10. Fijarse el tema de las tarjetas de los productos en el main del home, ya que no muestra a los productos en una fila de 4 elementos, solo de 1 y de 2. Se podrían agregar labels o un título a cada campo del login y registro, para que sea más claro a la hora de rellenarlo.

**Comment by AnitaMigueles** [comment]
Gracias Euge!! A último momento borré una media y se ve que me olvidé de revisar si seguía todo en orden
